[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "django>=6.0",
    "gunicorn>=22.0",
    "python-dotenv>=1.0.0",
    "dj-database-url>=2.0.0",
    "psycopg2-binary>=2.9.0",
    "django-bootstrap5>=24.0",
]
